### ISSUE TITLE
Is it expected that: state_machine_call_with_proof() does not return a proof when running with option checks_none

### ISSUE THREAD

**Issue by simonsso** [paritytech/try-runtime-cli#53]
In `core/src/commands/on_runtime_upgrade.rs` there are two calls to `state_machine_call_with_proof()` in the later is run without checks
 `UpgradeCheckSelect::None.encode().as_ref(),`

Is it expected behavior for the seconds call to return an Empty Trie,  when running with pre and post check the proof Trie has the length 45.

This is related to the question I posted yesterday on stackoverflow:
https://substrate.stackexchange.com/questions/10351/try-runtime-failed-to-generate-compact-proof-trieerrorinvalidstateroot

**Comment by simonsso** [comment]
@liamaharon  is this a normal behavior, is my data a weird corner case?

**Comment by liamaharon** [comment]
Nope, that is a bug. Thanks for reporting.

**Comment by simonsso** [comment]
Files to reproduce can be downloaded from here:
https://github.com/simonsso/try-runtime-cli/releases/download/ticket-53/Ticket-53.tar.bz2

**Steps to reproduce:**

```
simson@tama:~/work/try-runtime-cli$ cargo run -- --runtime ticket-53/runtime_eden.wasm  on-runtime-upgrade snap -p ticket-53/snap
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/try-runtime --runtime ticket-53/runtime_eden.wasm on-runtime-upgrade snap -p ticket-53/snap`
[2023-11-07T01:49:55Z INFO  remote-ext] Loading snapshot from "ticket-53/snap"
✅ Loaded snapshot (2.01s)
[2023-11-07T01:49:58Z INFO  remote-ext] initialized state externalities with storage root 0x96461e4db4dbe53604e2f67063595d0f201a59e3635828680666f9aec6d6d259 and state_version V0
[2023-11-07T01:49:58Z INFO  try-runtime::cli] Original runtime [Name: RuntimeString::Owned("nodle-para")] [Version: 23] [Code hash: 0xae58...e0f9]
[2023-11-07T01:49:59Z INFO  try-runtime::cli] New runtime      [Name: RuntimeString::Owned("nodle-para")] [Version: 25] [Code hash: 0x7d7e...1ab5]
[2023-11-07T01:49:59Z INFO  try_runtime_core::commands::on_runtime_upgrade] 🔬 Running TryRuntime_on_runtime_upgrade with checks: PreAndPost
[2023-11-07T01:50:10Z INFO  runtime::collator-selection] Sorted 4 Invulnerables, upgraded storage to version 1
[2023-11-07T01:50:10Z INFO  runtime::multisig] [3664149] ✍️ Number of calls to refund and delete: 0
[2023-11-07T01:50:10Z INFO  runtime::frame-support] ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`
[2023-11-07T01:50:10Z ERROR runtime] panicked at /home/simson/nodle/chain/runtimes/eden/src/lib.rs:486:65:
    called `Result::unwrap()` on an `Err` value: Other("Unsupported upgrade: VERSION_RANGE should be (on-chain storage version + 1, current storage version)")
thread 'main' panicked at cli/main.rs:334:6:
called `Result::unwrap()` on an `Err` value: Input("failed to execute TryRuntime_on_runtime_upgrade: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x3fa07c - <unknown>!rust_begin_unwind\n    1: 0x5ea3 - <unknown>!core::panicking::panic_fmt::h3e1dd3d08288569e\n    2: 0x6366 - <unknown>!core::result::unwrap_failed::h8b3db0f11171b57b\n    3: 0xb5fe7 - <unknown>!<runtime_eden::Runtime as frame_try_runtime::runtime_decl_for_try_runtime::TryRuntimeV1<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,runtime_eden::RuntimeCall,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<runtime_eden::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<runtime_eden::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<runtime_eden::Runtime>,frame_system::extensions::check_mortality::CheckMortality<runtime_eden::Runtime>,frame_system::extensions::check_nonce::CheckNonce<runtime_eden::Runtime>,frame_system::extensions::check_weight::CheckWeight<runtime_eden::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<runtime_eden::Runtime>,pallet_sponsorship::ChargeSponsor<runtime_eden::Runtime>)>>>>::on_runtime_upgrade::h130ec453f55cd46e\n    4: 0x1bb7e1 - <unknown>!TryRuntime_on_runtime_upgrade\nnote: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by liamaharon** [comment]
Hey @simonsso, I'm actually unable to replicate this on any Polkadot testnet or mainnets.

I wonder if it's an issue with how the snapshot or runtime is being created.

Could you please share how I can compile that runtime file locally and download the snapshot?

**Comment by simonsso** [comment]
@liamaharon 

Files related to https://github.com/paritytech/try-runtime-cli/issues/53

```
git branch
* (HEAD detached at v0.3.4)

```
simson@tama:~/nodle/work/try-runtime-cli$ cargo run -- --runtime ticket-53/runtime_eden.wasm  on-runtime-upgrade --checks=none snap -p ticket-53/snap
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/try-runtime --runtime ticket-53/runtime_eden.wasm on-runtime-upgrade --checks=none snap -p ticket-53/snap`
[2023-11-07T03:56:43Z INFO  remote-ext] Loading snapshot from "ticket-53/snap"
✅ Loaded snapshot (2.08s)
[2023-11-07T03:56:46Z INFO  remote-ext] initialized state externalities with storage root 0x96461e4db4dbe53604e2f67063595d0f201a59e3635828680666f9aec6d6d259 and state_version V0
[2023-11-07T03:56:46Z INFO  try-runtime::cli] Original runtime [Name: RuntimeString::Owned("nodle-para")] [Version: 23] [Code hash: 0xae58...e0f9]
[2023-11-07T03:56:47Z INFO  try-runtime::cli] New runtime      [Name: RuntimeString::Owned("nodle-para")] [Version: 25] [Code hash: 0xdd47...f334]
[2023-11-07T03:56:47Z INFO  try_runtime_core::commands::on_runtime_upgrade] 🔬 Running TryRuntime_on_runtime_upgrade with checks: None
[2023-11-07T03:56:58Z INFO  runtime::frame-support] ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`
[2023-11-07T03:56:58Z ERROR try-runtime::cli] failed to generate compact proof: TrieError(InvalidStateRoot(0x868e46de038c23f89652a0763c83831c852728f5d1e42ea98181364ff6c6ce22))
[2023-11-07T03:56:58Z INFO  try-runtime::cli] PoV size (zstd-compressed compact proof): 10 B. For parachains, it's your responsibility to verify that a PoV of this size fits within any relaychain constraints.
[2023-11-07T03:56:58Z INFO  try-runtime::cli] Consumed ref_time: 0s (0.00% of max 0.5s)
[2023-11-07T03:56:58Z INFO  try-runtime::cli] ✅ TryRuntime_on_runtime_upgrade executed without errors or weight safety warnings. Please note this does not guarantee a successful runtime upgrade. Always test your runtime upgrade with recent state, and ensure that the weight usage of your migrations will not drastically differ between testing and actual on-chain execution.
```

same result on main with this data

**Comment by simonsso** [comment]
@liamaharon  So I think there is something very fishy I was doing in the build above.

**Comment by liamaharon** [comment]
Yeah I was unable to reproduce this using your `master` branch and the snapshot provided above.

<img width="1183" alt="Screenshot 2023-11-07 at 09 33 33" src="https://github.com/paritytech/try-runtime-cli/assets/16665596/6dd9e757-a46c-4a06-9903-9f38a180b431">

Seems like a problem upstream with that build?

**Comment by simonsso** [comment]
@liamaharon  did you try with the wasm I shared?

I got this problem while working with the migrations and it is not yet merged on master, I created a branch where I can reproduce it:
https://github.com/NodleCode/chain/tree/iso/patch-1

**Comment by liamaharon** [comment]
I was able to reproduce with the runtime you provided in the `.tar`.

I suggest bisecting the commit history to find where things broke.

**Comment by simonsso** [comment]
Still working on same branch as above:
This https://github.com/NodleCode/chain/commit/87ee3fa2664c9c71cb5994db70139acdbffbd01d commit removes the error for me, so what in this input has changed?

```
simson@tama:~/nodle/chain$ ./scripts/try_runtime.sh 
    Finished release [optimized] target(s) in 0.38s
⚡ Found 3 strongly connected components which includes at least one cycle each
cycle(001) ∈ α: ApprovalVoting ~~{"DisputeCoordinatorMessage"}~~> DisputeCoordinator ~~{"ApprovalVotingMessage"}~~>  *
cycle(002) ∈ β: CandidateBacking ~~{"StatementDistributionMessage"}~~> StatementDistribution ~~{"CandidateBackingMessage"}~~>  *
cycle(003) ∈ γ: NetworkBridgeRx ~~{"GossipSupportMessage"}~~> GossipSupport ~~{"NetworkBridgeRxMessage"}~~>  *
   Compiling runtime-eden v2.3.1 (/home/simson/nodle/chain/runtimes/eden)
warning: unused imports: `AccountId`, `Balance`, `Decode`, `Encode`, `frame_support::Blake2_128Concat`, `pallet_uniques::CollectionDetails`
  --> runtimes/eden/src/migrations.rs:9:10
   |
9  |     codec::{Decode, Encode},
   |             ^^^^^^  ^^^^^^
10 |     frame_support::Blake2_128Concat,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 |     pallet_uniques::CollectionDetails,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12 |     primitives::{AccountId, Balance},
   |                  ^^^^^^^^^  ^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `state`
  --> runtimes/eden/src/migrations.rs:67:18
   |
67 |     fn post_upgrade(state: Vec<u8>) -> Result<(), TryRuntimeError> {
   |                     ^^^^^ help: if this is intentional, prefix it with an underscore: `_state`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `runtime-eden` (lib) generated 2 warnings (run `cargo fix --lib -p runtime-eden` to apply 2 suggestions)
   Compiling nodle-parachain v2.3.1 (/home/simson/nodle/chain/node)
    Finished release [optimized] target(s) in 50.49s
[2023-11-07T08:22:58Z INFO  remote-ext] Loading snapshot from "snapshots/eden2"
✅ Loaded snapshot (0.71s)
[2023-11-07T08:22:59Z INFO  remote-ext] initialized state externalities with storage root 0x96461e4db4dbe53604e2f67063595d0f201a59e3635828680666f9aec6d6d259 and state_version V0
[2023-11-07T08:22:59Z INFO  try-runtime::cli] Original runtime [Name: RuntimeString::Owned("nodle-para")] [Version: 23] [Code hash: 0xae58...e0f9]
[2023-11-07T08:22:59Z INFO  try-runtime::cli] New runtime      [Name: RuntimeString::Owned("nodle-para")] [Version: 25] [Code hash: 0x4408...264a]
[2023-11-07T08:23:00Z INFO  try_runtime_core::commands::on_runtime_upgrade] 🔬 Running TryRuntime_on_runtime_upgrade with checks: PreAndPost
[2023-11-07T08:23:01Z INFO  runtime::multisig] [3664149] ✍️ Number of calls to refund and delete: 0
[2023-11-07T08:23:01Z INFO  runtime::frame-support] ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`
[2023-11-07T08:23:01Z INFO  try_runtime_core::commands::on_runtime_upgrade] 🔬 TryRuntime_on_runtime_upgrade succeeded! Running it again without checks for weight measurements.
[2023-11-07T08:23:01Z INFO  runtime::frame-support] ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`
[2023-11-07T08:23:01Z INFO  try-runtime::cli] PoV size (zstd-compressed compact proof): 528 B. For parachains, it's your responsibility to verify that a PoV of this size fits within any relaychain constraints.
[2023-11-07T08:23:01Z INFO  try-runtime::cli] Consumed ref_time: 0s (0.00% of max 0.5s)
[2023-11-07T08:23:01Z INFO  try-runtime::cli] ✅ TryRuntime_on_runtime_upgrade executed without errors or weight safety warnings. Please note this does not guarantee a successful runtime upgrade. Always test your runtime upgrade with recent state, and ensure that the weight usage of your migrations will not drastically differ between testing and actual on-chain execution.
```

**Comment by simonsso** [comment]
> This [NodleCode/chain@87ee3fa](https://github.com/NodleCode/chain/commit/87ee3fa2664c9c71cb5994db70139acdbffbd01d) commit removes the error for me

@liamaharon  was above helpful in understanding this behavior?

**Comment by liamaharon** [comment]
It might be something to do with the state you're using being incompatible with the new runtime you are compiling.

**Comment by liamaharon** [comment]
Hey @simonsso any update here?

**Comment by simonsso** [comment]
@liamaharon I get other errors now in my integration. I think we can close this investigation and leave it here as a clue if this becomes a problem again in the future
